#!/bin/sh
# RC Script for Tiny Core Linux
# (c) Robert Shingledecker 2004-2012

# Mount /proc.
[ -f /proc/cmdline ] || /bin/mount /proc

# Remount rootfs rw.
/bin/mount -o remount,rw /

# Mount system devices from /etc/fstab.
/bin/mount -a

/etc/init.d/tc-config >/dev/kmsg 2>&1

# Enable USB console
modprobe libcomposite >/dev/kmsg 2>&1
modprobe g_serial >/dev/kmsg 2>&1
